estimator:
  pickle: model.pkl

strategy:
  name: gp
  params:
    acquisition: { name : ei, params : {}}

search_space:
  n_hidden:
    min: 1
    max: 300
    type: int

  l1_reg:
    min: 1e-7
    max: 1e-1
    type: float
    warp: log

  l2_reg:
    min: 1e-7
    max: 1e-1
    type: float
    warp: log

  learning_rate:
    min: 1e-4
    max: 1e1
    type: float
    warp: log
  
cv:
  name: kfold
  params:
    n_splits: 3
    shuffle: False

dataset_loader:
  name: joblib
  params:
    filenames: data.pkl
    x_name: x
    y_name: y


trials:
    uri: sqlite:///osprey-trials3.db
